### ISSUE TITLE
Add photo walks

### ISSUE THREAD

**Issue by tapaswenipathak** [tapaswenipathak/Photography-Competitions#11]

**Comment by anuragsarkar** [comment]
Do I need to add photo walks events and groups ?

**Comment by tapaswenipathak** [comment]
On Wed, May 15, 2019 at 8:49 AM Anurag Sarkar <notifications@github.com> wrote:
>
> Should I add photo walks events and groups ?

On the listed genres in this repository, yea.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.



-- 
Tapasweni
