### ISSUE TITLE
Text is invisible on the website

### ISSUE THREAD

**Issue by tapaswenipathak** [tapaswenipathak/Photography-Competitions#14]
<img width="1248" alt="Screen Shot 2019-05-16 at 5 19 00 AM" src="https://user-images.githubusercontent.com/4143778/57816764-258a4b80-779a-11e9-8540-721f87183368.png">

**Comment by anuragsarkar** [comment]
[Please check this](https://blooming-shelf-78804.herokuapp.com/) Let me know any further changes required.

**Comment by tapaswenipathak** [comment]
Can you add the theme from https://github.com/tapaswenipathak/Open-Source-Programs? The theme repository should be having this theme.

**Comment by anuragsarkar** [comment]
[Please check now](https://blooming-shelf-78804.herokuapp.com/)
