### ISSUE TITLE
Add PR template 

### ISSUE THREAD

**Issue by tapaswenipathak** [tapaswenipathak/Photography-Competitions#8]
Any addition should be written in index.html.

**Comment by prateekj117** [comment]
@tapaswenipathak I would like to work on this.

**Comment by tapaswenipathak** [comment]
On Sat, May 11, 2019 at 11:58 PM Prateek Jain <notifications@github.com> wrote:
>
> @tapaswenipathak I would like to work on this.

Sure!
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.



-- 
Tapasweni
